name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: fastify/github-action-merge-dependabot@v2.0.0
      with:
        github-token: ${{ secrets.mytoken }}
