# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
      NPM_AUTH: ${{secrets.NPM_AUTH}}
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run verify
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH" > ~/.npmrc
      - run: npm whoami
      - run: git remote add pub https://$GH_TOKEN@github.com/Bedrock-Layouts/Bedrock.git
      - run: git fetch pub master
      - run: git checkout master
      - run: git config --global user.name  'Jarvis1010'
      - run: git config --global user.email  'travis.mair@gmail.com'
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: npx lerna publish --git-remote pub --conventional-commits --yes
